window.SCT = {
  services: [
    {
      title: "Web Development",
      desc: "Modern, responsive and high-performance websites and landing pages.",
      label: "HTML · CSS · JS · React",
      icon: "web",
    },
    {
      title: "Business Systems",
      desc: "Custom systems designed to improve business operations, management and automation.",
      label: "Node · SQL · APIs",
      icon: "system",
    },
    {
      title: "Web Applications",
      desc: "Interactive platforms and applications built around real user needs.",
      label: "Full-stack · Product",
      icon: "app",
    },
    {
      title: "Mobile Applications",
      desc: "Modern mobile experiences for businesses and digital products.",
      label: "Responsive · React Native",
      icon: "mobile",
    },
    {
      title: "UI/UX Design",
      desc: "Clean, intuitive interfaces designed around usability and business objectives.",
      label: "Figma · Systems",
      icon: "ux",
    },
    {
      title: "Maintenance & Support",
      desc: "Continuous improvements, technical maintenance, optimization and support.",
      label: "Perf · Care",
      icon: "care",
    },
  ],
  stack: [
    {
      name: "HTML",
      group: "frontend",
      x: 18,
      y: 28,
      about: "Structure for every product interface.",
    },
    {
      name: "CSS",
      group: "frontend",
      x: 32,
      y: 18,
      about: "Layout, motion and visual systems.",
    },
    {
      name: "JavaScript",
      group: "frontend",
      x: 48,
      y: 26,
      about: "Interaction, logic and product behaviour.",
    },
    {
      name: "TypeScript",
      group: "frontend",
      x: 64,
      y: 18,
      about: "Typed interfaces for durable applications.",
    },
    {
      name: "React",
      group: "frontend",
      x: 78,
      y: 30,
      about: "Component-driven product UIs.",
    },
    {
      name: "Node.js",
      group: "backend",
      x: 22,
      y: 58,
      about: "Runtime for APIs and services.",
    },
    {
      name: "Express",
      group: "backend",
      x: 40,
      y: 68,
      about: "Lean HTTP layers and routing.",
    },
    {
      name: "PostgreSQL",
      group: "backend",
      x: 58,
      y: 58,
      about: "Relational data for serious products.",
    },
    {
      name: "MySQL",
      group: "backend",
      x: 74,
      y: 66,
      about: "Reliable storage for business systems.",
    },
    {
      name: "Git",
      group: "tools",
      x: 28,
      y: 86,
      about: "Versioned work, reviewable history.",
    },
    {
      name: "GitHub",
      group: "tools",
      x: 48,
      y: 84,
      about: "Collaboration and public engineering.",
    },
    {
      name: "Figma",
      group: "tools",
      x: 66,
      y: 86,
      about: "Interface design before a line of code.",
    },
    {
      name: "REST APIs",
      group: "tools",
      x: 84,
      y: 78,
      about: "Contracts between clients and systems.",
    },
  ],
  links: [
    [0, 1],
    [1, 2],
    [2, 3],
    [3, 4],
    [2, 5],
    [5, 6],
    [6, 7],
    [7, 8],
    [5, 9],
    [9, 10],
    [10, 11],
    [7, 12],
    [4, 12],
  ],
  projects: [
    {
      id: "auracodex",
      name: "AuraCodeX",
      category: "experiments",
      categoryLabel: "BrandWebProduct",
      desc: "Digital solutions and software development brand — identity, presence and product thinking under one system.",
      tech: ["Brand", "Web", "Product"],
      url: "#contact",
      github: null,
    },
    {
      id: "grow-games",
      name: "Grow Games",
      category: "systems",
      categoryLabel: "Business system",
      desc: "Management system for a gaming and LAN house environment: sessions, operations and day-to-day control.Private project — details are available upon request.",
      tech: ["Node.js", "MySQL", "Dashboard"],
      url: "#contact",
      github: null,
    },
    // {
    //   id: "pescalink",
    //   name: "PescaLink MZ",
    //   category: "applications",
    //   categoryLabel: "Application",
    //   desc: "Digital platform connecting fishing and logistics services across Mozambique.",
    //   tech: ["Web app", "APIs", "Ops"],
    //   url: "#contact",
    //   github: null
    // },
    {
      id: "restaurant",
      name: "Restaurant Platform",
      category: "systems",
      categoryLabel: "System",
      desc: "Digital ecosystem for restaurants: menus, orders and reservations in one operational flow.",
      tech: ["Node.js", "PostgreSQL", "UX"],
      url: "https://aura-code-x.vercel.app/projects_ACX/restaurant-landing-prototype/index.html",
      github: null,
    },
    {
      id: "aura-imovision",
      name: "Aura Imovision",
      category: "websites",
      categoryLabel: "Website",
      desc: "Real-estate digital experience and property showcase platform — browsing, presenting, converting.",
      tech: ["Frontend", "CMS-ready", "SEO"],
      url: "https://aura-code-x.vercel.app/projects_ACX/restaurant-landing-prototype/index.html",
      github: null,
    },
  ],
};
